# Generated by Django 6.0.3 on 2026-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10),
        ),
    ]
