# Generated by Django 6.0.3 on 2026-03-12 18:07

import Users.models.info_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_infomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Esta activo?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='¿Es del personal?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='¿Es administrador?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Personal'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Users.models.info_model.upload_image_to_db, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
